<script lang="ts">
  import Nav from "../../components/Nav.svelte";
  import { onMount } from "svelte";
	import ai_percentages from "../../data/ai_percentages";
	import Chart from "chart.js/auto";

	Chart.defaults.color = "#fff";

	let chart: HTMLCanvasElement
	onMount(() => {
		new Chart(chart, {
			type: 'bar',
			data: {
				labels: ai_percentages.word,
				datasets: [{
					label: 'ChatGPT',
					data: ai_percentages.percentages,
					borderWidth: 1
				}]
			},
			options: {
				scales: {
					y: {
						beginAtZero: true
					}
				}
			}
		});
	})
</script>

<Nav activeTab="data" />
<h2 class="text-3xl">The Data</h2>
<p>
  The data consists of 42,000 documnents. It consists of two parts, text created by humans and text generated with ChatGPT.
  The human text was gathered from a dataset of 1 million answers and questions from Yahoo answers.
  The ChatGPT text was collected by asking ChatGPT the same questions that were asked from the human answers using the OpenAI API.
</p>

<p>The top words in documents generated by ChatGPT and the percentage of documents that these words appear in</p>
<div>
  <canvas bind:this={chart}></canvas>
</div>