<script lang="ts">
  import Nav from "../../components/Nav.svelte";
  import { onMount } from "svelte";
	import ai_percentages from "../../data/ai_percentages";
  import word_counts from '../../data/word_counts'
	import Chart from '../../components/Chart.svelte'

  const maxTokenCount = Math.max(...word_counts.map((item) => item.x))
  const tokensLabels = Array.from(new Array(maxTokenCount)).map((_, i) => i + 1)

  const humanScatter = word_counts.filter(({ backgroundColor }) => backgroundColor === 'blue')
  const aiScatter = word_counts.filter(({ backgroundColor }) => backgroundColor === 'red')
</script>

<Nav activeTab="data" />
<h2 class="text-3xl">The Data</h2>
<p>
  The data consists of 42,000 documnents. It consists of two parts, text created by humans and text generated with ChatGPT.
  The human text was gathered from a dataset of 1 million answers and questions from Yahoo answers.
  The ChatGPT text was collected by asking ChatGPT the same questions that were asked from the human answers using the OpenAI API.
</p>
<a href="https://github.com/rustybucket-cloud/chatgpt-detection-app/blob/main/notebooks/data.ipynb" class="hover:bg-indigo-400 rounded p-2 mt-3" target="_blank">View how the data was collected</a>

<p class="mt-6">The top words in documents generated by ChatGPT and the percentage of documents that these words appear in</p>
<Chart type="bar" labels={ai_percentages.word} datasets={[{ label: 'ChatGPT', data: ai_percentages.percentages, borderWidth: 1}]} title="Top Words in Documents Generated by ChatGPT" yAxisLabel="Percentage of documents used in" xAxisLabel="Word" />
<Chart type="scatter" labels={tokensLabels} datasets={[{ label: 'Human', data: humanScatter, backgroundColor: 'rgba(0, 0, 255, 0.5)' }, { label: 'ChatGPT', data: aiScatter, backgroundColor: 'rgba(255, 0, 0, 0.5)' }]} title="Unique Token Usage by Document" yAxisLabel="Percentage of Unique Tokens" xAxisLabel="Total Number of Tokens" />